### PR TITLE
Make it possible to return a React Element from getLabel again

### PR DESCRIPTION
**Pull request by RafaelKr**
The commit https://github.com/react-navigation/react-navigation-drawer/commit/980e054cddb9e1ad54956c69a8fc08434b07a7c8 makes it impossible to return a Element from getLabel.

In the current version you end up with an error like
`Invariant Violation: 749,RCTView,31,[object Object] is not usable as a native method argument`

And the red screen shows the error
`Malformed calls from JS: field sizes are different.`

**This change could break code which is using `getLabel` to return a React element.**  
In the first version of this PR I introduced the additional function `getAccessibilityLabel` that wasn't as performant and you had to add more code to use it as my current version.

### CODE REVIEW

**Comment by satya164** [comment]
> I introduced the additional function getAccessibilityLabel that wasn't as performant

Why isn't it performant? We support such prop in other places, so I think makes sense to do siilar here for consistency

**Comment by RafaelKr** [comment]
You have to do the "loop" twice, once for getLabel and once for getAccessibilityLabel.
So I have to fetch my translations twice.

But for consistency I could also add the `getAccessibilityLabel` function.
So getLabel can either return
```{
  element: <React.Element>,
  accessibilityLabel: <string>
}```
or only `<React.Element>`, but then `getAccessibilityLabel` must return a string

**Comment by satya164** [comment]
> You have to do the "loop" twice, once for getLabel and once for getAccessibilityLabel.

It'll be called in the same loop if I understand correctly. Even if there were 2 loops I highly doubt it'll be the perf issue.

> So I have to fetch my translations twice.

Why? Can you give some code example? Your code should never rely on how many times this function is called. If it's expensive, memoize it.

> So getLabel can either return

I don't like having 2 APIs to do the same thing. I'll defer to @brentvatne on this.

**Comment by RafaelKr** [comment]
It's only one loop, but It's calling 2 functions, which both need to get the label text.  
But I thought again about it and you're right, it would add to much complexity to implement both options (Object/React element). I'll just add the getAccessibilityLabel function again.

But anyway here's a code example of how I currently implemented it:
```tsx
renderDrawerItemLabel = (scene: any) => {
    this.counter++

    const labelText: string = this.props.t(`PAGES.${this.props.getLabel(scene)}`)
    const style: any = {
      container: drawerItemStyles.container,
      text: drawerItemStyles.text,
    }

    if (scene.focused) {
      style.container = drawerItemStyles.containerFocused
      style.text = drawerItemStyles.textFocused
    } else if (this.counter % 2) {
      style.container = drawerItemStyles.containerOdd
    }

    return {
      accessibilityLabel: labelText,
      element: (
        <View style={style.container}>
          <Text style={style.text}>
            {labelText}
          </Text>
        </View>
      ),
    }
  }
```

**Comment by RafaelKr** [comment]
Here's my updated code:

```
rDrawerItemLabel = (scene: any) => {
  this.counter++

  const style: any = {
    container: drawerItemStyles.container,
    text: drawerItemStyles.text,
  }

  if (scene.focused) {
    style.container = drawerItemStyles.containerFocused
    style.text = drawerItemStyles.textFocused
  } else if (this.counter % 2) {
    style.container = drawerItemStyles.containerOdd
  }

  return (
    <View style={style.container}>
      <Text style={style.text}>
        {this.props.t(`PAGES.${this.props.getLabel(scene)}`)}
      </Text>
    </View>
  )
}

getDrawerItemAccessibilityLabel = (scene: any) => this.props.t(`PAGES.${this.props.getLabel(scene)}`)

render() {
  return (
    <SafeAreaView style={styles.container} forceInset={{ top: 'always', horizontal: 'never' }}>
      <ScrollView style={styles.itemListContainer}>
        <View style={styles.menuCaptionContainer}>
          <Text style={styles.menuCaption}>{this.props.t('Menu')}</Text>
        </View>
        <DrawerItems
          {...this.props}
          onItemPress={this.onItemPressHandler}
          getLabel={this.renderDrawerItemLabel}
          getAccessibilityLabel={this.getDrawerItemAccessibilityLabel}
        />
      </ScrollView>
    </SafeAreaView>
  )
}
```

**Comment by satya164** [comment]
Closing since the PR isn't necessary.

**Pull request closed without merging**
